apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Python Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    steps:
      # Step 1: Checkout
      - name: Checkout Code
        uses: https://github.com/cloudbees-io/checkout@v1

      # Step 2: Run inside Python container
      - name: Run Tests in Python
        uses: docker://python:3.10
        run: |
          pip install pytest selenium webdriver-manager
          python -m pytest -v