apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Python Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    steps:
      - name: Checkout Code
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Install Dependencies
        run: |
          pip install pytest

      - name: Run Tests
        run: |
          python -m pytest -v