apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Selenium Python Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    steps:
      # Checkout repo
      - name: Checkout Code
        uses: https://github.com/cloudbees-io/checkout@v1

      # Run inside Selenium container (BEST OPTION)
      - name: Run Selenium Tests
        uses: docker://selenium/standalone-chrome
        run: |
          apt-get update
          apt-get install -y python3 python3-pip

          pip3 install pytest selenium webdriver-manager

          pytest -v