apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow
on:
  push:
    branches:
      - main
jobs:
  test-job:
    steps:
      - name: Checkout Code
        uses: https://github.com/cloudbees-io/checkout@v1
      - name: Run Tests
        uses: docker://python:3.10
        run: |
          apt-get update
          apt-get install -y wget unzip curl fonts-liberation libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcb-dri3-0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2

          # Install Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          apt install -y ./google-chrome-stable_current_amd64.deb || apt-get install -f -y

          pip install pytest selenium webdriver-manager

          pytest -v